### ISSUE TITLE
Does Cartesi Machine trace execute on chain?

### ISSUE THREAD

**Issue by raindust** [cartesi/dave#60]
The white paper of Cartesi tells me that about the Cartesi Machines in the blockchain part, when settling the dispute the contract in the blockchain will execute the exact step in which the attacker disagrees with the defender. But in dave's contract source code, I find that it only computes the Merkle root hash in https://github.com/cartesi/dave/blob/da760687b7f0b37642a1aed0703299657926fe8d/prt/contracts/src/Commitment.sol#L16-L30 at the end of sealMatch function.
Am I missing something?

**Comment by GCdePaula** [comment]
The onchain execution of a disagreeing state-transition function can be found on [cartesi/machine-solidity-step](https://github.com/cartesi/machine-solidity-step).

**Comment by raindust** [comment]
Thanks!
