### ISSUE TITLE
Custom arbitration parameters

### ISSUE THREAD

**Issue by guidanoli** [cartesi/dave#85]
## Problem statement

As of now, the following arbitration parameters are hard-coded:

- `LEVELS`: depth of tournament
- `log2step`: $log_2$ of meta steps between leaves in computation Merkle tree
- `height`: height of computation Merkle tree

Their values are calculated based by the `prt/measure_constants` tool.
In order to change the value of these parameters, the developer currently has to edit the source code.
This hinders development and testing.

## Proposed solution

Move these parameters to a separate contract, whose address is passed down during construction time, and stored as an immutable variable, so that it can be more cheaply consulted via message calls. Its interface would have one function for each parameter. Libraries that would consult these parameters from `ArbitrationConstants` now may receive this contract as parameter. This contract may be called `ArbitrationParameters`?

**Comment by guidanoli** [comment]
What do you think, @GCdePaula ?

**Comment by GCdePaula** [comment]
I like this idea! Have you considered using the tournament factory for this?

I believe all contracts already hold this address, and it makes sense that these configurations be part of the factory (there should be "canonical" constants on the "canonical" factory).

It could make sense to have (meta)step in this factory too.

**Comment by guidanoli** [comment]
> Have you considered using the tournament factory for this?

No, I have not, but I agree that it makes sense, because, in a multi-level tournament, all sub-tournaments should share the same arbitration parameters.

> It could make sense to have (meta)step in this factory too.

Sorry, I'm not particularly familiar with this part of the codebase. However, I guess it also makes sense, since, in the context of the same multi-level tournament, the (meta)step should be the same.

**Comment by guidanoli** [comment]
@stephenctw told me that there are some other parameters which also need to be customizable:

- `COMMITMENT_EFFORT`
- `CENSORSHIP_TOLERANCE`
- `MATCH_EFFORT`

PS: `MAX_ALLOWANCE` is calculated from `CENSORSHIP_TOLERANCE` and `COMMITMENT_EFFORT`.
